//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketNetz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.EventTicket = new HashSet<EventTicket>();
        }
    
        public int bookingNbr { get; set; }
        public string bookingDate { get; set; }
        public int customerNbr { get; set; }
    
        public virtual ICollection<EventTicket> EventTicket { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
