//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketNetz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventTicket = new HashSet<EventTicket>();
        }
    
        public string eventName { get; set; }
        public string eventDate { get; set; }
        public double baseTicketPrice { get; set; }
        public string venueName { get; set; }
    
        public virtual ICollection<EventTicket> EventTicket { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
