//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketNetz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Event = new HashSet<Event>();
        }
    
        public string venueName { get; set; }
        public string city { get; set; }
        public string seatCapacity { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
    }
}
